sonar.projectKey=HireConnect_Frontend
sonar.projectName=HireConnect Frontend
sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.token=squ_0ad1ae22a8b38e995a262981813704b321cba6e6
sonar.javascript.lcov.reportPaths=coverage/lcov.info
